### ISSUE TITLE
Nature publication points to inexistent repository

### ISSUE THREAD

**Issue by cobalamin** [BC19RG/LongCovid#1]
Hi,

your publication in Nature, at https://www.nature.com/articles/s41591-021-01433-3, currently points to the inexistent repository https://github.com/BC19RG/NatureMedicine2021. 

I'm guessing that the easiest fix would be renaming this repository accordingly, since [you can rename your GitHub repo without breaking any links](https://stackoverflow.com/a/16602311/3090225).

**Comment by BC19RG** [comment]
Hi Simon
Thank you for pointing this out. I had comments about not finding the repo, but wasn’t aware of the name change.
I have renamed the repo now, and hopefully everything is working perfectly.
Karl


From: Simon ***@***.***>
Reply to: BC19RG/LongCovid ***@***.***>
Date: Friday, 25 June 2021 at 11:36
To: BC19RG/LongCovid ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BC19RG/LongCovid] Nature publication points to inexistent repository (#1)


Hi,

your publication in Nature, at https://www.nature.com/articles/s41591-021-01433-3, currently points to the inexistent repository https://github.com/BC19RG/NatureMedicine2021.

I'm guessing that the easiest fix would be renaming this repository accordingly, since you can rename your GitHub repo without breaking any links<https://stackoverflow.com/a/16602311/3090225>.

**Comment by cobalamin** [comment]
Sure, thank you for the quick reaction! :+1:
